server.port=${PORT:8080}

# Supabase PostgreSQL Database Connection via Environment Variables
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# LLM API Properties
llm.api.url=https://api.groq.com/openai/v1/chat/completions
llm.api.key=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
